/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdio.h>

#include "uart.h"
#include "timer.h"
#include "systick.h"


uint16_t sevensd = 0;


int main(void) {

	uart_init();
	tim2_init();

	while(1) {

		sevensd = tim2_rd();
		printf("Value is %u\r\n", (unsigned) sevensd);
	}

	return 0;
}
