/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdio.h>

#include "led.h"
#include "rotary.h"
#include "systick.h"


int main(void) {
	uint8_t btn;

	led_init();
	rsw_init();

	while(1) {

		btn = rsw_rd();

		if (btn)  {
			led_on();
		}
		else {
			led_off();
		}

		systick_ms_delay(10);
	}

	return 0;
}
