/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdio.h>
#include "buzzer.h"
#include "systick.h"


int main(void) {

	buzzer_init();

	while(1) {
		buzzer_on();
		systick_ms_delay(500);
		buzzer_off();
		systick_ms_delay(500);
	}


	return 0;
}
